name: Composite Workflow

on:
  workflow_dispatch:

jobs:
  composite-job:
    uses: ./.github/workflows/blank.yml
  composite-job2:
    uses: harshmittal-cyber/composite2work/.github/workflows/blank2.yml@main

