name: Composite Workflow

on:
  workflow_dispatch:

jobs:
  composite-job:
    uses: ./.github/workflows/blank.yml
  composite-job2:
    uses: harshmittal-cyber/composite2work/.github/workflows/blank2.yml@main
  composite-job3:
    runs-on: ubuntu-latest
    steps:
      - name: action checkout
        uses: actions/checkout@v2
      - name: call local action
        uses: ./.github/workflows/blank.yml
