name: Composite Workflow

on:
  workflow_dispatch:

jobs:
  composite-job:
    uses: ./.github/workflows/blank.yml
  composite-job2:
    uses: harshmittal-cyber/composite2work/.github/workflows/blank2.yml@main
  composite-job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Step 1 of the composite workflow"

      - name: Call Reusable Workflow 1
        uses: ./.github/workflows/blank.yml

      - name: Step 2
        run: echo "This is Step 2 of the composite workflow"

      - name: Call Reusable Workflow 2
        uses: ./.github/workflows/blank2.yml

      - name: Step 3
        run: echo "This is Step 3 of the composite workflow"

