name: Composite Workflow

on:
  workflow_dispatch:

jobs:
  composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Step 1 of the composite workflow"

      - name: Call Reusable Workflow 1
        uses: ./.github/workflows/reusable-workflow1.yml

      - name: Step 2
        run: echo "This is Step 2 of the composite workflow"

      - name: Call Reusable Workflow 2
        uses: ./.github/workflows/reusable-workflow2.yml

      - name: Step 3
        run: echo "This is Step 3 of the composite workflow"
